version: '3.8'
services:
  plugin-builder:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    working_dir: /EmbyRecs
    volumes:
      - .:/EmbyRecs
      - ./output:/EmbyRecs/bin/Release
    command: >
      sh -c "dotnet build EmbyRecs/Plugin.csproj -c Release && cp /EmbyRecs/bin/Release/net6.0/*.dll /EmbyRecs/bin/Release/"